feat(course.*.ts): implemented createCrourse controller
lmsGenie/server pull request #27
Opened 2023-11-09 04:56 UTC by sub1120

Summary:
By this change a user will be able to create a course draft with basic details. User also will be
able to create  categories.

Changes:
1. Update the course model as per requirement.
2. Added createCourse controller, service, validation, and route.
3. Added createCategory controller, service, validation, and route.

2023-11-09 05:56 UTC, shivamvijaywargi requested changes
Please check the comments.

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/controllers/v1/course.controller.ts
> +  return commonResponse(res, "Category created successfully", category);
You need to pass the status code created else it is gonna be 200 and not 201

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/controllers/v1/course.controller.ts
> +  return commonResponse(res, "Category created successfully", category);
Change the status code for other things, because by default it is 200

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/enums/index.ts
> +  MONTHS = "MONTHS",
Do we really need months?

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/models/course.model.ts
> +  type: "MAIN_CATEGORY" | "SUB_CATEGORY";
We have this in the enum, can we not use it?

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/models/course.model.ts
> +    enum: ["MAIN_CATEGORY", "SUB_CATEGORY"],
We have this in the enum.

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/models/course.model.ts
> +      max: [100, "Course rating cannot be greater than 100"],
Course rating under percentage? And that to up to 100?

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/models/course.model.ts
> +const CategoryModel = model<ICategory>("Category", categorySchema);
Doesn't look like you added the category in the course schema, correct me if I am wrong.

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/routes/v1/course.route.ts
> +    validate(courseValidation.createCourseSchema),
Add proper role authorisations.

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/routes/v1/course.route.ts
> +    validate(courseValidation.createCategorySchema),
Here also add authorised roles.

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/routes/v1/course.route.ts
> + * @ROUTE {{URL}}/api/v1/course
Always make the route word plural instead of course it should be courses.

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/routes/v1/index.ts
> +    path: "/course",
/courses

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/services/course.service.ts
> +const createCategory = async (type: string, name: string) => {
Let's separate the category into it's own service.

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/utils/language.ts
> +  "SPANISH",
If we are creating languages we should give the option to the instructor to create language instead of hard coding them.

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
Category is going to be a string or the ID which will be referred to?

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +    language: z.enum(LANGUAGE_LIST as [string, ...string[]], {
Can you please explain this?

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +      [
You can use Object.Values() instead of writing individually.

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +          DURATION_UNITS.MINUTES,
Same here as well Object.values()

2023-11-09 05:56 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +    type: z.enum([CATEGORY_TYPES.MAIN_CATEGORY, CATEGORY_TYPES.SUB_CATEGORY], {
Object.values()

2023-11-09 14:31 UTC, sub1120 commented
> Please check the comments.

Thanks for your time reviewing my PR. I will work on comments soon.

2023-11-09 14:40 UTC, sub1120 commented on src/enums/index.ts
> +  MONTHS = "MONTHS",
I think not required, because mostly course duration is mentioned in days. I will remove it MONTHS.

2023-11-09 14:45 UTC, sub1120 commented on src/models/course.model.ts
> +  type: "MAIN_CATEGORY" | "SUB_CATEGORY";
Oh! yes I forgot about it. I will use here. Thanks.

2023-11-09 15:15 UTC, sub1120 commented on src/controllers/v1/course.controller.ts
> +  return commonResponse(res, "Category created successfully", category);
Got it. I will update status codes.

2023-11-09 15:21 UTC, sub1120 commented on src/models/course.model.ts
> +const CategoryModel = model<ICategory>("Category", categorySchema);
There are two fields in course schema `category`, `subcategory`.

2023-11-09 15:25 UTC, sub1120 commented on src/routes/v1/course.route.ts
> + * @ROUTE {{URL}}/api/v1/course
Noted. I will update it.

2023-11-09 15:40 UTC, sub1120 commented on src/routes/v1/course.route.ts
> +    validate(courseValidation.createCourseSchema),
Got it. I will add 

```javascript
isLoggedIn,
    authorizeRoles(
      ROLES_LIST.ADMIN,
      ROLES_LIST.INSTRUCTOR,
),```

Is it good?

2023-11-09 15:44 UTC, sub1120 commented on src/routes/v1/course.route.ts
> +    validate(courseValidation.createCategorySchema),
```javascript
isLoggedIn, 
authorizeRoles (
     ROLES_LIST.ADMIN, 
     ROLES_LIST.INSTRUCTOR,
),
```
Is it good for now?

2023-11-09 15:49 UTC, sub1120 commented on src/routes/v1/index.ts
> +    path: "/course",
Got it.

2023-11-09 15:49 UTC, sub1120 commented on src/services/course.service.ts
> +const createCategory = async (type: string, name: string) => {
Nice suggestion. I will make it.

2023-11-09 16:59 UTC, sub1120 commented on src/validations/course.validation.ts
> +    language: z.enum(LANGUAGE_LIST as [string, ...string[]], {
Ya sure, suppose our all values of `enum` are `string`, and as per definition of  `z.enum`, 1st parameter should be of type `[string, ...string[]]`, by this type it only allow an non empty string array. 

In our case, since we already know variable `LANGUAGE_LIST` is a non empty array of string, so I have used typescript assertion `as` to satisfy the given type. 

Please let me know, if I am going right.

2023-11-09 17:07 UTC, sub1120 commented on src/services/course.service.ts
> +const createCategory = async (type: string, name: string) => {
Shivam, should we separate controller, router, and validation too for category?

2023-11-09 17:08 UTC, sub1120 commented on src/validations/course.validation.ts
> +          DURATION_UNITS.MINUTES,
Got it. I will update.

2023-11-09 17:08 UTC, sub1120 commented on src/validations/course.validation.ts
> +      [
Got it. I will update.

2023-11-09 17:19 UTC, sub1120 commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
It will be `string`. Correct me if i am wrong, here we are using zod to validate request body data right? If so, category field will be some id with `string` type only.

2023-11-09 18:36 UTC, sub1120 commented
@shivamvijaywargi , I have worked on all comments. Also implemented slug generation. Please review it.

2023-11-13 13:23 UTC, shivamvijaywargi reviewed
Food work, please check the comments

2023-11-13 13:33 UTC, sub1120 commented on src/enums/index.ts
> +export enum DURATION_UNITS {
Sure, we can make it. I will.

2023-11-13 13:39 UTC, sub1120 commented on src/helpers/slugGenerator.ts
> +const createSlug = (value: string) => {
Ya that's right, but creating a separate function also reduces code redundancy. 

For now, it will restrict everyone to use default parameters, but later we can allow some parameters to be passed, as per our need.

2023-11-13 13:41 UTC, sub1120 commented on src/middlewares/auth.middleware.ts
> +export const authorizeRoles = (...roles: ROLES_LIST[]) =>
no problem. I copied it from your unmerged PR only. 😄

2023-11-13 13:43 UTC, shivamvijaywargi commented on src/helpers/slugGenerator.ts
> +const createSlug = (value: string) => {
I understand your point but let's solve the problems we have today and not worry about the problems of tomorrow, what do you say?

2023-11-13 13:45 UTC, sub1120 commented on src/validations/course.validation.ts
> +        message: "Course subtitle must be at least 2 characters",
Oh! my bad. I will correct it and will try to not make this kind of mistakes again.

2023-11-13 13:45 UTC, sub1120 commented on src/validations/course.validation.ts
> +        message: "Course subtitle cannot be more than 80 characters ",
Got it. I will correct it here also.

2023-11-13 13:45 UTC, shivamvijaywargi commented on src/helpers/slugGenerator.ts
> +const createSlug = (value: string) => {
Okay, let's leave it to it.

2023-11-13 13:46 UTC, sub1120 commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
Okay, let me check this.

2023-11-13 13:47 UTC, sub1120 commented on src/validations/course.validation.ts
> +    language: z.enum(LANGUAGE_LIST as [string, ...string[]], {
Okay, I will run and provide you with a sample API response.

2023-11-13 15:36 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
/(ObjectId\(')?[0-9a-fA-F]{24}('\))?/  --> Here this is the RegEx

2023-11-13 15:36 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +    language: z.enum(LANGUAGE_LIST as [string, ...string[]], {
Sure

2023-11-13 16:04 UTC, sub1120 commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
Thanks for Regex. I will use it.

2023-11-13 16:21 UTC, sub1120 commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
Shivam, should we use `ObjectId` in regex? I think frontend will send only string without `ObjectId`. 

See this response from POST `/category`. _id is a string without including `ObjectId`.
```JSON
{
	"success": true,
	"message": "Category created successfully",
	"data": {
		"type": "SUB_CATEGORY",
		"name": "Full Stack",
		"_id": "6552446938229b860aa4d053",
		"__v": 0
	}
}
```

2023-11-13 16:24 UTC, sub1120 commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
Although its optional in Regex, but currently, we don't have written code in `course.service.ts` to handle, `ObjectId(string)` type of Ids. It will throw error as below,

```JSON
{
	"success": false,
	"message": "Course validation failed: category.0: Cast to [ObjectId] failed for value \"[ 'ObjectId(654d23dfaf15a46080bd6530)' ]\" (type string) at path \"category.0\" because of \"CastError\", subCategory.0: Cast to [ObjectId] failed for value \"[ 'ObjectId(6552446938229b860aa4d053)' ]\" (type string) at path \"subCategory.0\" because of \"CastError\"",
	"stack": "ValidationError: Course validation failed: category.0: Cast to [ObjectId] failed for value \"[ 'ObjectId(654d23dfaf15a46080bd6530)' ]\" (type string) at path \"category.0\" because of \"CastError\", subCategory.0: Cast to [ObjectId] failed for value \"[ 'ObjectId(6552446938229b860aa4d053)' ]\" (type string) at path \"subCategory.0\" because of \"CastError\"\n    at model.Document.invalidate (/app/node_modules/.pnpm/mongoose@7.4.5/node_modules/mongoose/lib/document.js:3162:32)\n    at model.$set (/app/node_modules/.pnpm/mongoose@7.4.5/node_modules/mongoose/lib/document.js:1453:12)\n    at model.$set (/app/node_modules/.pnpm/mongoose@7.4.5/node_modules/mongoose/lib/document.js:1113:16)\n    at model.Document (/app/node_modules/.pnpm/mongoose@7.4.5/node_modules/mongoose/lib/document.js:164:12)\n    at model.Model (/app/node_modules/.pnpm/mongoose@7.4.5/node_modules/mongoose/lib/model.js:123:12)\n    at new model (/app/node_modules/.pnpm/mongoose@7.4.5/node_modules/mongoose/lib/model.js:4691:15)\n    at /app/node_modules/.pnpm/mongoose@7.4.5/node_modules/mongoose/lib/model.js:2913:18\n    at Array.map (<anonymous>)\n    at Function.create (/app/node_modules/.pnpm/mongoose@7.4.5/node_modules/mongoose/lib/model.js:2902:30)\n    at Object.createCourse (/app/src/services/course.service.ts:16:36)"
}
```

2023-11-13 16:28 UTC, sub1120 commented on src/validations/course.validation.ts
> +    language: z.enum(LANGUAGE_LIST as [string, ...string[]], {
Shivam, here is sample API request/response. Please check.

Route : POST `courses/`
Request Body: 

```json
{
    "title":"MERN Course",
    "subTitle": "Complete guide to MERN",
    "category": "654d23dfaf15a46080bd6530",
    "subCategory":"6552446938229b860aa4d053",
    "language":"ENGLISH",
    "topic":"full stack web development with mern",
    "courseLevel":"BEGINNER",
    "courseDuration":{
			"unit": "DAYS",
			"value":90
		}
}
```

Response Body:
```json
{
	"success": true,
	"message": "Course created successfully",
	"data": {
		"title": "MERN Course",
		"subTitle": "Complete guide to MERN",
		"category": [
			"654d23dfaf15a46080bd6530"
		],
		"subCategory": [
			"6552446938229b860aa4d053"
		],
		"slug": "mern-course",
		"language": "ENGLISH",
		"topic": [
			"full stack web development with mern"
		],
		"courseOutline": [],
		"targetAudience": [],
		"preRequisites": [],
		"courseLevel": "BEGINNER",
		"reviews": [],
		"instructors": [],
		"totalEnrollments": 0,
		"courseDuration": {
			"unit": "DAYS",
			"value": 90
		},
		"_id": "65524e0cf720c1422ac41b16",
		"createdAt": "2023-11-13T16:25:48.260Z",
		"updatedAt": "2023-11-13T16:25:48.260Z",
		"__v": 0
	}
}
```

2023-11-13 18:09 UTC, sub1120 commented on src/services/course.service.ts
> +  const slug = createSlug(title);
Shivam, I found below ways to tackle this, please suggest.

Method 1: Check for already existed slug. If slug is already present. We will modify the slug by appending a random string (https://www.npmjs.com/package/crypto-random-string). 

Example: 
`courses/mern-course`
`courses/mern-course-2cf05d`
`courses/mern-course-134dng`

This method involves small overhead to check for already existed slug in db.

Method 2: Use id + slug in URLs. This way we don't need to maintain unique slugs.
Example 
`courses/6552446938229b860aa4d053/mern-course`
`courses/6552446938229b860aa4dasd/mern-course`
`courses/6552446938229b860asdd15d/mern-course`

This method has no overhead, but URL looks little wired.

2023-11-13 18:26 UTC, shivamvijaywargi commented
First method is what we need.

On Mon, Nov 13, 2023, 11:39 PM Subham Sahu ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/services/course.service.ts
> <https://github.com/lmsGenie/server/pull/27#discussion_r1391491772>:
>
> > @@ -0,0 +1,33 @@
> +import createSlug from "@/helpers/slugGenerator";
> +import CourseModel from "@/models/course.model";
> +
> +const createCourse = async (
> +  title: string,
> +  subTitle: string,
> +  category: string,
> +  subCategory: string,
> +  language: string,
> +  topic: string,
> +  courseLevel: string,
> +  courseDuration: string,
> +) => {
> +  const slug = createSlug(title);
>
> Shivam, I found below ways to tackle this, please suggest.
>
> Method 1: Check for already existed slug. If slug is already present. We
> will modify the slug by appending a random string (
> https://www.npmjs.com/package/crypto-random-string).
>
> Example:
> courses/mern-course
> courses/mern-course-2cf05d
> courses/mern-course-134dng
>
> This method involves small overhead to check for already existed slug in
> db.
>
> Method 2: Use id + slug in URLs. This way we don't need to maintain unique
> slugs.
> Example
> courses/6552446938229b860aa4d053/mern-course
> courses/6552446938229b860aa4dasd/mern-course
> courses/6552446938229b860asdd15d/mern-course
>
> This method has no overhead, but URL looks little wired.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lmsGenie/server/pull/27#discussion_r1391491772>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHBG5BYY7FYTADSZ4NVM2ELYEJO6BAVCNFSM6AAAAAA7D6MYECVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMRXHEZDMMBTGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-14 06:34 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
Did we type it as a string anywhere?
If not I will check it once I reach home.

2023-11-14 06:34 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +    language: z.enum(LANGUAGE_LIST as [string, ...string[]], {
We still have Day as a unit?

2023-11-14 06:35 UTC, shivamvijaywargi reviewed
Nice work so far, please check the last few and we should be good to go

2023-11-14 06:39 UTC, sub1120 commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
Nope, model has following types

```javascript
category: [
      {
        type: Schema.Types.ObjectId,
        ref: "Category",
        required: [true, "Course category is required"],
      },
    ],
    subCategory: [
      {
        type: Schema.Types.ObjectId,
        ref: "Category",
        required: [true, "Course sub category is required"],
      },
    ],
```

It will allow either a valid ObjectId `string` or an instance of  `ObjectId`.

2023-11-14 06:40 UTC, sub1120 commented on src/validations/course.validation.ts
> +    language: z.enum(LANGUAGE_LIST as [string, ...string[]], {
Yes, we only decided to remove `MONTHS`.

2023-11-14 06:41 UTC, sub1120 commented on src/enums/index.ts
> +export enum DURATION_UNITS {
Done.

2023-11-14 06:41 UTC, sub1120 commented on src/validations/course.validation.ts
> +        message: "Course subtitle cannot be more than 80 characters ",
Done

2023-11-14 06:42 UTC, sub1120 commented on src/validations/course.validation.ts
> +        message: "Course subtitle must be at least 2 characters",
Done

2023-11-14 06:48 UTC, sub1120 commented
> Nice work so far, please check the last few and we should be good to go

Thanks. I have made changes. Once you reach home, go through all comments. Take your time, no hurry.

2023-11-14 08:13 UTC, sub1120 commented on src/services/course.service.ts
> +  const slug = createSlug(title);
Done. Update in `courseSchema.pre("save",)`

2023-11-21 18:34 UTC, shivamvijaywargi commented on src/models/course.model.ts
> +    this.slug = `${newSlug}-${uniqueString.slice(-6, uniqueString.length)}`;
What is the guarantee that the last 6 characters of a MongoDB ID will always be unique?

2023-11-21 18:36 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +    language: z.enum(LANGUAGE_LIST as [string, ...string[]], {
`MONTHS` and I think. we can remove `DAYS` as well. How about we only have content in hours? Or the courses are gonna be in live format?

2023-11-21 18:38 UTC, shivamvijaywargi commented on src/services/course.service.ts
> +  const slug = createSlug(title);
Checked and commented, please check.

2023-11-21 18:39 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
I will try to check this today in the evening (if possible)

2023-11-22 16:50 UTC, sub1120 commented on src/models/course.model.ts
> +    this.slug = `${newSlug}-${uniqueString.slice(-6, uniqueString.length)}`;
Please check specifications for Object Id once (https://www.mongodb.com/docs/manual/reference/method/ObjectId/), if i am not wrong, last 3 bytes (6 characters) are generated by incrementing counter, so every new value will be different from previous one. 

Yes, counter can repeat values after 6^6 possible permutations, but this case won't happen because instructor will not make these many request for any particular course title. Let me know, if you know any better idea for it.

2023-11-22 16:54 UTC, sub1120 commented on src/validations/course.validation.ts
> +    language: z.enum(LANGUAGE_LIST as [string, ...string[]], {
I think you are right, let's first focus on per-recorded courses. I will remove `DAYS`.

2023-11-22 16:54 UTC, sub1120 commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
Sure

2023-11-22 17:22 UTC, sub1120 commented on src/validations/course.validation.ts
> +    language: z.enum(LANGUAGE_LIST as [string, ...string[]], {
Done.

2023-12-24 05:21 UTC, shivamvijaywargi commented on src/models/course.model.ts
> +    this.slug = `${newSlug}-${uniqueString.slice(-6, uniqueString.length)}`;
This is not just for one instructor, it could be 100s if not 1000s of instructors uploading/updating the course.

2023-12-24 05:24 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
We do not have ObjectId but the string itself is a ObjectId type, this RegEx will check if the string is a valid ObjectId or not, if it is not then it will throw an error, else it will pass it.

2023-12-24 06:16 UTC, sub1120 commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
```js
.regex(/[0-9a-fA-F]{24}/, {
        message: "Course subcategory id is invalid",
 }),
```

Check this validation, i have added for category and subcategory id.

2023-12-24 06:27 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
Test it once, but AFAIR I have used this zod validation z.string().regex(/(ObjectId\(')?[0-9a-fA-F]{24}('\))?/g) to validte ObjectIds.

2023-12-24 06:30 UTC, sub1120 commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
From frontend, we will send object id like ObjectId("fsdfdsfdsf") or just "fsdfdsfdsf". I think second one.

2023-12-24 06:30 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
^[a-f0-9]{24}$


Use this

2023-12-24 06:33 UTC, sub1120 commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
Okay. This seems correct. Thanks

2023-12-24 06:35 UTC, shivamvijaywargi commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
^[0-9a-fA-F]{24}$

Use this

2023-12-24 06:36 UTC, sub1120 commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
Okay

2023-12-24 07:56 UTC, sub1120 commented on src/validations/course.validation.ts
> +        invalid_type_error: "Course category must be a string",
Done

2023-12-24 13:30 UTC, shivamvijaywargi commented on src/models/course.model.ts
> +    this.slug = `${newSlug}-${uniqueString.slice(-6, uniqueString.length)}`;
Any news on this?

2023-12-25 02:36 UTC, shivamvijaywargi reviewed
Done

2023-12-25 02:54 UTC, shivamvijaywargi approved these changes

2023-12-25 02:55 UTC, merged